-- =============================================================================
-- FlatPlanet Security Platform — Test Data Seed
-- PRE-REQUISITE: V5 migration must be applied first.
-- Run once via Supabase SQL Editor.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$
DECLARE
    v_company_id        UUID;
    v_admin_id          UUID;
    v_user_id           UUID;

    -- App
    v_app_hub           UUID;

    -- Platform role (pre-seeded by V1)
    v_role_owner        UUID;

    -- dashboard-hub roles & permissions
    v_hub_role_admin    UUID;
    v_hub_role_user     UUID;
    v_hub_role_viewer   UUID;
    v_hub_perm_read     UUID;
    v_hub_perm_write    UUID;
    v_hub_perm_manage   UUID;

BEGIN

-- -----------------------------------------------------------------------
-- 1. Company
-- -----------------------------------------------------------------------
INSERT INTO companies (name, country_code, status)
VALUES ('FlatPlanet', 'PH', 'active')
RETURNING id INTO v_company_id;

-- -----------------------------------------------------------------------
-- 2. Users (id auto-generated by V5, password_hash bcrypt via pgcrypto)
-- -----------------------------------------------------------------------
INSERT INTO users (company_id, email, full_name, role_title, password_hash, status)
VALUES (v_company_id, 'chris.moriarty@flatplanet.com', 'Chris Moriarty', 'Platform Owner',
        crypt('D0g@C@t&R@t', gen_salt('bf', 11)), 'active')
RETURNING id INTO v_admin_id;

INSERT INTO users (company_id, email, full_name, role_title, password_hash, status)
VALUES (v_company_id, 'user@flatplanet.com', 'Test User', 'Staff',
        crypt('User@1234!', gen_salt('bf', 11)), 'active')
RETURNING id INTO v_user_id;

-- -----------------------------------------------------------------------
-- 3. App — FlatPlanet Development Hub (the only SP-registered app)
--    Platform API (HubApi) is a backend service, not a user-facing app.
--    Individual projects (e.g. Tala) are managed inside HubApi, not here.
-- -----------------------------------------------------------------------
INSERT INTO apps (company_id, name, slug, base_url, status, registered_by)
VALUES (v_company_id, 'FlatPlanet Development Hub', 'dashboard-hub',
        'https://fpdevelopmenthub.netlify.app', 'active', v_admin_id)
RETURNING id INTO v_app_hub;

-- -----------------------------------------------------------------------
-- 4. Assign platform_owner role to Chris on dashboard-hub
-- -----------------------------------------------------------------------
SELECT id INTO v_role_owner FROM roles WHERE name = 'platform_owner' AND is_platform_role = true;

INSERT INTO user_app_roles (user_id, app_id, role_id, granted_by, status)
VALUES (v_admin_id, v_app_hub, v_role_owner, v_admin_id, 'active');

-- -----------------------------------------------------------------------
-- 5. dashboard-hub — roles
-- -----------------------------------------------------------------------
INSERT INTO roles (app_id, name, description, is_platform_role)
VALUES (v_app_hub, 'Admin', 'Full access within the Hub', false)
RETURNING id INTO v_hub_role_admin;

INSERT INTO roles (app_id, name, description, is_platform_role)
VALUES (v_app_hub, 'User', 'Can create and manage own projects', false)
RETURNING id INTO v_hub_role_user;

INSERT INTO roles (app_id, name, description, is_platform_role)
VALUES (v_app_hub, 'Viewer', 'Read-only access to assigned projects', false)
RETURNING id INTO v_hub_role_viewer;

-- -----------------------------------------------------------------------
-- 5a. dashboard-hub — permissions
-- -----------------------------------------------------------------------
INSERT INTO permissions (app_id, name, description, category)
VALUES (v_app_hub, 'read_data', 'View projects and activity', 'data')
RETURNING id INTO v_hub_perm_read;

INSERT INTO permissions (app_id, name, description, category)
VALUES (v_app_hub, 'write_data', 'Create and edit projects', 'data')
RETURNING id INTO v_hub_perm_write;

INSERT INTO permissions (app_id, name, description, category)
VALUES (v_app_hub, 'manage_settings', 'Configure Hub settings', 'admin')
RETURNING id INTO v_hub_perm_manage;

-- -----------------------------------------------------------------------
-- 5b. dashboard-hub — role → permission mappings
-- -----------------------------------------------------------------------
INSERT INTO role_permissions (role_id, permission_id) VALUES
    (v_hub_role_admin,  v_hub_perm_read),
    (v_hub_role_admin,  v_hub_perm_write),
    (v_hub_role_admin,  v_hub_perm_manage),
    (v_hub_role_user,   v_hub_perm_read),
    (v_hub_role_user,   v_hub_perm_write),
    (v_hub_role_viewer, v_hub_perm_read);

-- -----------------------------------------------------------------------
-- 6. Assign test user (Viewer) on dashboard-hub
-- -----------------------------------------------------------------------
INSERT INTO user_app_roles (user_id, app_id, role_id, granted_by, status)
VALUES (v_user_id, v_app_hub, v_hub_role_viewer, v_admin_id, 'active');

RAISE NOTICE 'Seed complete. Company: %, Admin: %, User: %', v_company_id, v_admin_id, v_user_id;

END $$;
